### ISSUE TITLE
[aac @ 00000124243c2600]

### ISSUE THREAD

**Issue by cndhng** [raryelcostasouza/pyTranscriber#16]
![image](https://user-images.githubusercontent.com/83151768/195745868-b4984b32-f870-48dc-88e4-1183f9c1190f.png)
 Although I do not understand this error message, I do not see the output files have an error. What is this error mean? Thank you

**Comment by raryelcostasouza** [comment]
What type of file are you trying to import? Did you try with a different file? If the file is corrupted it can cause errors when processing it.

**Comment by cndhng** [comment]
I do import mp4 movie files. How do you know if a media file is corrupted?

**Comment by raryelcostasouza** [comment]
If you try a different file and it works normally you would know that the failed file has some sort of issue.
