### ISSUE TITLE
What are some reason that the program doesn't produce output file and exits itself?

### ISSUE THREAD

**Issue by cndhng** [raryelcostasouza/pyTranscriber#17]
Hello, I do really like batch transcribing where you can add multiple files and leave your PC on to have the transcription job done. However, I notice that every time a video cannot be transcribed, the program exits itself without any alarms or notifications. So I always have to automatically skip a file in the list by myself and re-add the next item in the list. Is there a possible way that you can add a feature where error files would be skipped and progress to the next one? Thank you

**Comment by raryelcostasouza** [comment]
Are you running Windows? 
Doesn't the program show some error messages on the command line screen that opens when you launch the app? If you can provide those it can be helpful to fix it.

**Comment by cndhng** [comment]
I do not see any command line, in fact, even with succeeded transcriptions I do not really see the command lines. It remains like this 
![image](https://user-images.githubusercontent.com/83151768/195961726-301ec006-de0e-4ffc-b301-f82896d9e699.png)

**Comment by raryelcostasouza** [comment]
By your windows style looks like you running a linux distro, right? if so could you please try to run the app from the terminal and check what output you get

**Comment by cndhng** [comment]
Nope, I actually just run the prog normally and it opens pyTranscribe and the cmd like thescreenshot shown, I'm running on Win11, I do not use Linux

**Comment by raryelcostasouza** [comment]
I see... the random crashes on windows are a known issue... unfortunately the library that does the multithreading processing has some issues when the code gets compiled... but they happen more often on Windows than Linux. As those crashes are at library internal level it's not easy to catch them... but I will keep a note to see what can be done on next update.
