### ISSUE TITLE
Transcribe stuck in step 1: Converting speech regions to FLAC files

### ISSUE THREAD

**Issue by rgm-code** [raryelcostasouza/pyTranscriber#18]
<img width="1020" alt="截圖 2022-10-15 上午10 22 27" src="https://user-images.githubusercontent.com/111717474/195965505-ed7e7e82-b34f-431d-96f4-ffe4b995bb0e.png">

**Comment by raryelcostasouza** [comment]
Did you try with a different file? What macOS version are you running?
