### ISSUE TITLE
API support to allow use in python scripts

### ISSUE THREAD

**Issue by erobert98** [raryelcostasouza/pyTranscriber#19]
**Is your feature request related to a problem? Please describe.**
Is it possible to use this inside another python script. I have a script that downloads videos into MP4 format and would like to use this with that script to create the file with the transcription without using the full GUI.

**Describe the solution you'd like**
An API of sorts to call on mp4 files that will transcribe the video.

If this is already possible, could you point me in the right direction to be able to accomplish this.

**Comment by raryelcostasouza** [comment]
For that you can just use the backend tool autosub https://github.com/agermanidis/autosub

**Comment by raryelcostasouza** [comment]
pyTranscriber is a GUI on top of that... so autosub can run from command line and be used on other scripts...
