### ISSUE TITLE
Disabling the command prompt

### ISSUE THREAD

**Issue by Brancliff** [raryelcostasouza/pyTranscriber#20]
Whenever I open PyTranscribe, a command prompt also comes alongside it.

![image](https://user-images.githubusercontent.com/22332774/196797021-4780605e-d6e8-4e81-81c3-eece80e6fa75.png)

I can't enter anything in it, and the GUI seems to have everything I'd need. If I run into a problem, both the GUI and the command prompt crash, so the presence of the terminal doesn't give me any extra feedback. Could we get a way to just disable it appearing at all? Closing it closes both it and the GUI.

**Comment by raryelcostasouza** [comment]
I will keep a note for that on next release. Thanks!
