### ISSUE TITLE
Android and iOS versions of the app

### ISSUE THREAD

**Issue by NuraliMedeu** [raryelcostasouza/pyTranscriber#22]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to transcribe movies saved on a phone.

**Describe the solution you'd like**
Android and iOS versions of the app with at least the basic functionality.

**Describe alternatives you've considered**
Copying movies from the phone to a PC and transcribing them using the desktop app, which is cumbersome if you need a transcription while traveling.

**Additional context**
N/A

**Comment by i990049** [comment]
you should use web online translator, such as IBM or Amazon.

**Comment by raryelcostasouza** [comment]
Thanks for the suggestions.
