### ISSUE TITLE
Only 10 sentences can be output, and they are incomplete

### ISSUE THREAD

**Issue by msjsc001** [raryelcostasouza/pyTranscriber#23]
Hello.
Glad to use this software, I tested different videos and several different software versions (V1.5-V1.8) but all of them only output the first 10 sentences and those 10 sentences are also incomplete, can you fix this problem?

I am using windows 11 22H2 64 bit system

**Comment by msjsc001** [comment]
This is one of a series of videos that

https://user-images.githubusercontent.com/93178788/200101864-fa022c6b-355d-40b0-87f3-273cd88e42cb.mp4

**Comment by i990049** [comment]
我看你是中文界面，直接用中文回答
可以改用videosrt Pro、字幕组机翻小助手、nosub，有免费版和专业版，自己搜一下，b站有配置教程

**Comment by EllisMorrow** [comment]
> 

谢谢，我是觉得 pyTranscriber 用的是谷歌接口识别率高，其它收费的可能都没这个高，所以给开发者这个反馈。
win11 22h2 版本自带的那个 实时字幕功能，识别率比谷歌接口的都高，要是能利用那个就更好了，现在也没开发者写。

**Comment by i990049** [comment]
> > 
> 
> 谢谢，我是觉得 pyTranscriber 用的是谷歌接口识别率高，其它收费的可能都没这个高，所以给开发者这个反馈。 win11 22h2 版本自带的那个 实时字幕功能，识别率比谷歌接口的都高，要是能利用那个就更好了，现在也没开发者写。

那是你根本没用过国内的，文字翻译英译中这一块，网易见外比谷歌微软百度好得多，直接拿生肉自带的英文字幕，网易的机翻相对比较通顺，其他三家的机翻比较生硬；语音翻译这一块，谷歌翻译现在也退出中国了，你自己改dns或者爬墙用吧，不会就用上面前面那个videosrt Pro语雀，其实也是调用大厂的key，阿里的可以免费三个月每天两小时，企鹅的可以每个月免费10小时，嫌少可以去用subtitle edit里面的视频翻译whisper，也要爬墙，听说比kalid/vosk好一些，不过开源免费的东西很难跟商业模型比的，后者资金雄厚数据库庞大。Win11没用过，微软总喜欢自作多情升级系统然后又禁止我用word宏代码，Adobe pr 2022听说也能识别语音，不过听说识别中文很烂，识别英文还行；剪映海外版也能识别七八国语音，不过你要找专门的工具才能导出字幕，而且导出来的字幕完全没有标点符号，甲乙丙丁四个人轮流说了几句话，中间一个标点符号都没有，免费的果然不是最好的。

**Comment by EllisMorrow** [comment]
> > > 
> > 
> > 
> > 谢谢，我是觉得 pyTranscriber 用的是谷歌接口识别率高，其它收费的可能都没这个高，所以给开发者这个反馈。win11 22h2 版本自带的那个 实时字幕功能，识别率比谷歌接口的都高，要是能利用那个就更好了，现在也没开发者写。
> 
> 那是你根本没用过国内的，文字翻译英译中这一块，网易见外比谷歌微软百度好得多，直接拿生肉自带的英文字幕，网易的机翻相对比较通顺，其他三家的机翻比较生硬;语音翻译这一块，谷歌翻译现在也退出了中国，你自己改dns或者爬墙用吧，不会就用上面前面那个videosrt Pro语雀，其实也是调用大厂的key，阿里的可以免费三个月每天两小时，企鹅的可以每个月免费10小时，嫌少可以去用字幕编辑里面的视频翻译whisper，也要爬墙，听说比kalid/vosk好一些，不过开源免费的东西很难跟商业模型比的，后者资金雄厚数据库庞大。Win11没用过，微软总喜欢自作多情升级系统然后又禁止我用word宏代码，Adobe pr 2022听说也能识别语音，不过听说识别中文很烂，识别英文还行;剪映海外版也能识别七八国语音，不过你要找专门的工具才能导出字幕，而且导出来的字幕完全没有标点符号，甲乙丙丁四个人轮流说了几句话，中间一个标点符号都没有，免费的果然不是最好的。

谢谢推荐，很实用。

**Comment by EllisMorrow** [comment]
Other solutions have been found
