### ISSUE TITLE
Crash on select files (Manjaro Cinnamon)

### ISSUE THREAD

**Issue by Moilleadoir** [raryelcostasouza/pyTranscriber#24]
**Describe the bug**
The program crashes as soon as the Select Files button is clicked

**To Reproduce**
1. Run program
2. Click Select Files

**Expected behavior**
File selection dialogue should appear.

**Screenshots**
Command line output:
```
$ export LC_ALL=C; pyTranscriber
Gtk-Message: 18:03:57.385: Failed to load module "xapp-gtk3-module"
Gtk-Message: 18:03:57.386: Failed to load module "canberra-gtk-module"

(pyTranscriber:749722): Gtk-WARNING **: 18:03:59.540: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Aborted (core dumped)
```

**Desktop (please complete the following information):**
 - OS: Manjaro Linux with Cinnamon desktop

**Additional context**
Newly installed from AUR package `pytranscriber-bin`.

**Comment by raryelcostasouza** [comment]
Thanks for reporting. Could you please try this other linux version and let me know if it works? https://github.com/raryelcostasouza/pyTranscriber/releases/download/v1.8-stable/pyTranscriber-v1.8-linux-gnome40-wayland-portable.zip
