### ISSUE TITLE
possibility to vary the region-detection threshold?

### ISSUE THREAD

**Issue by aleks-mariusz** [raryelcostasouza/pyTranscriber#25]
**Is your feature request related to a problem? Please describe.**
I have some videos where the speakers tend to pause between parts of their sentence.  pyTranscriber seems to treat each of these pause as a separate "region", and so the translations are created 'in isolation' and are often incorrect.

Is there a way to vary the region-detection threshold? It looks like the parameter is called `min_region_size` per [this function](https://github.com/raryelcostasouza/pyTranscriber/blob/4bf80ed6beaf9c724fe28d160a67865861d9f6c6/autosub/__init__.py#L216) but i'm not sure how to make it so that this can be varied by the gui? 

**Is your feature request related to a problem? Please describe.**
yes, depending on speaker, the default region-detection threshold may need to be adjusted

**Describe the solution you'd like**
would be nice if this could be varied (or maybe even disabled so the entire file counts as a region, unless there's a reason that's undesireable)

**Describe alternatives you've considered**
i considered to see if the pyTranscriber.app macOS deployment can be editted but it looks like the code is encapsulated and non-modifiable there?

**Additional context**

**Comment by raryelcostasouza** [comment]
Hi @aleks-mariusz, 
In fact the binary distributions have code encapsulated... so unless you are skillful in compiling (instructions on docs folder) no easy way to change that.

If you are confortable with command line one suggestion is to try using [autosub](https://github.com/agermanidis/autosub) directly with that property edited. I confess I never tweaked that so I'm not sure how helpful will that be in your case.

**Comment by raryelcostasouza** [comment]
If you try that in autosub and it is effective in solving your issue please let me know so we can add an option from pyTranscriber to edit that in future release.

Thanks

**Comment by aleks-mariusz** [comment]
Hi Raryel, thanks for the incredibly fast reply.  I did peak at autosub however the repo says it's not currently maintained and that its last commit is from 4 years ago, so i wasn't sure if that'll work.  I'll give it a try and let you know if it makes a difference!

**Comment by raryelcostasouza** [comment]
Hi aleks, that is the underlying library that pyTranscriber uses on background with almost no modifications... it should still be runnable

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by aleks-mariusz** [comment]
Ok, i see.. so i gave autosub a try.. after modifying the min_region_size parameter to 15 seconds.. i got, still pretty lousy results.  I've uploaded both the [resulting .SRT file](https://pastebin.com/WUTPYwL0) as well as [a .SRT file](https://pastebin.com/sM6rFTyY) generated by uploading [a sample video](https://www.mediafire.com/file/trv342cj9e7puhk/2.5-Weekly-Update-Vid.mp4/file) to [youtube](https://www.youtube.com/watch?v=4Gp3HrT9tHU).  The sample one is less than 20 minutes, while i have dozens of real working set of videos are almost identical, except 80-120 minutes long, so a bit impractical to upload to youtube just to get subtitles :-/ 

If you have a few minutes, can you take a look a these, and let me know why the one from youtube is so incredibly accurate, whereas the one autosub outputs is basically rubbish, even though they both use google?

I'm baffled how to make this app usable if it's not the smaller regions sizes :-/
