### ISSUE TITLE
No network connection, please solve it Thank you

### ISSUE THREAD

**Issue by huchen482436** [raryelcostasouza/pyTranscriber#26]
Hello author, I'm a Chinese user, and your software experience is very good. I used it once before, but today it doesn't work. I tried a lot of network lines, such as the United States, Japan, Germany, Canada, Australia, Singapore, Korea, Britain, and VPN Error Unable to access Google Voice Server. Is my network wrong or just caught up with the software maintenance? Thank you. I hope you can reply.
![J8YY2NP4MD 5@%NSYO 35%I](https://user-images.githubusercontent.com/87387634/208100593-9217a47a-e1f4-4400-b53b-2b9cf89bf712.png)

**Comment by raryelcostasouza** [comment]
Hi, you can search for a proxy server that works on your country and fill the details at pyTranscriber proxy settings... or use a desktop-wide VPN app like Windscribe

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
