### ISSUE TITLE
Temporary folder is created, causing issue with firewall

### ISSUE THREAD

**Issue by luxoflux** [raryelcostasouza/pyTranscriber#27]
First, I would like to thank you for this invaluable and powerful program that you continue to develop. I use it routinely.

Here's my issue: On Windows, a temporary folder is created (```AppData\Local\Temp\onefile_*```) - but because I use a firewall, I have to whitelist ```main.exe``` in this random folder each time I run the program. Previously, I only needed to allow ```pyTranscriber.exe```, which was easier because its location doesn't change.

Please consider reverting to the previous behavior, or including the necessary files in the same folder for portability.

Thanks.

(This is may be the problem with #26.)

**Comment by raryelcostasouza** [comment]
Hi Luxoflux, 
Thanks for reporting.
Before this version the app would also extract itself to temp folder before running. It's been like that for many years and this is the first time someone reports this issue.

I suggest you create a whilelist rule that includes all suffixes possible for that folder... something like AppData\Local\Temp\onefile_*

One alternative solution for future versions would be to have the installable version not extracting itself and the portable version extracting itself before running.

What firewall are you using?

**Comment by luxoflux** [comment]
Sorry, let me clarify. I just checked again and can confirm in version 1.8 and earlier the connections are made from ```pyTranscriber.exe```. In version 1.9 the connection is made from ```main.exe``` which is in a temporary, random folder.

v1.8:
![pytranscriber-1 8](https://user-images.githubusercontent.com/9421932/209750939-5044d7ff-560a-4e31-9f06-2e1679d0c881.png)

v1.9:
![pytranscriber-1 9](https://user-images.githubusercontent.com/9421932/209750979-7416c274-8421-48e0-b544-9f6b1b962cce.png)

**Comment by raryelcostasouza** [comment]
Hi @luxoflux 
Thanks for providing more details.

1 - Could you please check the full file path for pyTranscriber.exe on previous version.
2 - Which firewall app are you currently using?

**Comment by luxoflux** [comment]
1 - On v1.8 the file path is portable, so I can put it anywhere and it works fine.
2 - The firewall is called TinyWall, it's just a frontend for Windows Firewall that operates in whitelist-only mode.

Cheers.

**Comment by raryelcostasouza** [comment]
Hi @luxoflux 

As a workaround for now you can do the following:
1. Run the app
2. Copy the entire onefile temp folder to your desired location
3. Create a shortcut to the main.exe file there
4. Whitelist that fixed path on TinyWall

**Comment by raryelcostasouza** [comment]
And please let us know if that works in your case. Thanks

**Comment by luxoflux** [comment]
Your solution works well. Thank you!

**Comment by raryelcostasouza** [comment]
Glad to hear that @luxoflux
