### ISSUE TITLE
Flagged as a trojan on WIndows

### ISSUE THREAD

**Issue by cluthz** [raryelcostasouza/pyTranscriber#28]
On windows 10, MS defender:

Detected: Trojan:Win32/CryptInject
Detected: Trojan:Script/Wacatac.H!ml

file: C:\Users\...\Downloads\pyTranscriber-v1.9-win-portable.zip

**Comment by raryelcostasouza** [comment]
Hi @cluthz 
Thanks for reporting. 

We had this type of issues before. Python frozen apps are usually false flagged by AV.
I will submit for Microsoft for Analysis and this should stop happening on next couple of days.

Thanks

**Comment by raryelcostasouza** [comment]
Just submitted both to MS
![Screenshot from 2022-12-28 16-34-13](https://user-images.githubusercontent.com/2302068/209863439-6b17421b-fde3-493a-8577-6d4580626821.png)
![Screenshot from 2022-12-28 16-34-01](https://user-images.githubusercontent.com/2302068/209863444-e1c00f1e-5fac-4f2d-bfff-35e484489a86.png)

**Comment by sxzebra** [comment]
Same happened to Windows 11 with Crowdstrike

**Comment by raryelcostasouza** [comment]
Follows the Microsoft Analysis saying it is NOT a malware for installer binary and next version of definitions won't flag it anymore.
![image](https://user-images.githubusercontent.com/2302068/209952574-0d81904c-0a53-46e7-b221-450272d0eb63.png)

**Comment by raryelcostasouza** [comment]
Regarding portable version it's still being false positively flagged. Working on it.
As a workaround please please use the installer version for now if possible.

**Comment by raryelcostasouza** [comment]
The installer version is generated from the portable version using the Inno Setup script available at https://github.com/raryelcostasouza/pyTranscriber/blob/master/script-installer-windows.iss with no modifications on binary. 

So it's non sense the installer version being whitelisted and the portable being flagged... we resubmitted to Microsoft providing this details 
![image](https://user-images.githubusercontent.com/2302068/209955332-29e8ad92-c0a5-4d95-adfc-9eddbd152960.png)

**Comment by cluthz** [comment]
Thanks for your hard work.

I tried the installer version now, it is allowed to install, but as soon as I launch it, it get's flagged.
I did update windows defender and ran the commands suggested. Maybe I have to wait a day or two before updated are getting pushed?

```
C:\Program Files\Windows Defender>MpCmdRun.exe -removedefinitions -dynamicsignatures

Service Version: 4.18.2211.5
Engine Version: 1.1.19900.2
AntiSpyware Signature Version: 1.381.1331.0
AntiVirus Signature Version: 1.381.1331.0

Starting Dynamic Signature removal.
Done!

Service Version: 4.18.2211.5
Engine Version: 1.1.19900.2
AntiSpyware Signature Version: 1.381.1331.0
AntiVirus Signature Version: 1.381.1331.0

C:\Program Files\Windows Defender>MpCmdRun.exe -SignatureUpdate
Signature update started . . .
Signature update finished. No updates needed

C:\Program Files\Windows Defender>
```

**Comment by raryelcostasouza** [comment]
Portable version was also confirmed NOT to be malware:
![image](https://user-images.githubusercontent.com/2302068/210028823-46688add-7e26-42a0-b575-36d520f3cdb6.png)

Please update your Windows Defender definitions and retry. If you feel confortable with command line you may also try this commands provided by Microsoft to update your definitions:

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

**Comment by raryelcostasouza** [comment]
Hi @cluthz. You can try again tomorrow and let us know if the issue persists.

**Comment by cluthz** [comment]
I can confirm that it no longer flags as malware!

Thanks!

**Comment by raryelcostasouza** [comment]
Glad to hear that. You're welcome

**Comment by raryelcostasouza** [comment]
Hi users please retry with repacked version. Now the app does not extracts itself on every execution to temp folder... not triggering further alarms from major vendors. Thanks
