### ISSUE TITLE
pyTranscriber-v1.9-win-installer & AntiVirus

### ISSUE THREAD

**Issue by sami-soft** [raryelcostasouza/pyTranscriber#30]
pyTranscriber-v1.9-win-installer.exe » INNO » {app}\pyTranscriber.exe - a variant of Python/Packed.Nuitka.F suspicious application - cleaned by deleting !!!

**Comment by raryelcostasouza** [comment]
Please check https://github.com/raryelcostasouza/pyTranscriber/issues/28

**Comment by raryelcostasouza** [comment]
Hi @sami-soft  please retry with repacked version. Now the app does not extracts itself on every execution to temp folder... not triggering further alarms from major vendors. Thanks
