### ISSUE TITLE
pyTranscriberv1.9-win-portable IS A VIRUS

### ISSUE THREAD

**Issue by pokeslog** [raryelcostasouza/pyTranscriber#31]
https://www.virustotal.com/gui/file/e65f329bc59cf89f643466f15f96efa5e423356ddd11e63379c7fa71de80ac41

**Comment by raryelcostasouza** [comment]
Hi @hurricanz ... as per issue https://github.com/raryelcostasouza/pyTranscriber/issues/28 you can see it is just a false positive. You can see on detection list something Nuitka something... which is the python compiler I use https://github.com/Nuitka/Nuitka. As there are too many vendors with this false positive I will do some repacking changes that I believe will prevent that. Currently the app is a singlefile executable that self-extracts to temp folder on each run... and this seems to be the behavior that generates this false alerts.

**Comment by raryelcostasouza** [comment]
Hi @hurricanz please retry with repacked version. Now the app does not extracts itself on every execution to temp folder... not triggering further alarms from major vendors. Thanks
