### ISSUE TITLE
Thanks for this tool.. Is there any way to include an option to limit the number of words per line? I can't pinpoint how it breaks up the lines.

### ISSUE THREAD

**Issue by GodsITguy** [raryelcostasouza/pyTranscriber#34]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by raryelcostasouza** [comment]
Hi @GodsITguy, 
Thanks for feedback.
For now this feature is not available, but for now you can use notepad++ or other advanced such type of edits.
We will include in the list of features to consider for future versions.
Thanks

**Comment by GodsITguy** [comment]
One more thing I’m looking for that would be an awesome addition is a tool that generates subtitles like the captions in Instagram. You know the typing type or the various size text on a caption. I currently use your tool with subsimport in blender.
