### ISSUE TITLE
problems with the Linux .desktop file

### ISSUE THREAD

**Issue by silentJET85** [raryelcostasouza/pyTranscriber#37]
The .desktop file in the Linux installer has no Category defined, so the shortcut ends up in the Lost and Found area in the KDE menu.

Adding this line to pytranscriber.desktop would fix that:
`Categories=AudioVideo;`

Also, the shortcut does not get removed when running the uninstall script. This is because it's running the command:
`sudo rm -f /usr/share/applications/pyTranscriber.desktop` with a capital T. 
But the actual .desktop filename is all lowercase.

(I would've submitted a pull request, but these files don't appear to be part of the repo.)

**Comment by raryelcostasouza** [comment]
Sorry, I missed this notification. But I took note here and will include this change on next release 2.0.
