### ISSUE TITLE
Google Colab

### ISSUE THREAD

**Issue by Mennaruuk** [raryelcostasouza/pyTranscriber#38]
**Is your feature request related to a problem? Please describe.**
Is it possible to run pyTranscriber in Google Colab?

**Describe the solution you'd like**
I would like to run pyTranscriber through Google Colab. That way, I can make use of powerful NVIDIA Tesla T4 GPU. However, Google Colab doesn't appear to support GUI applications, only CLI.

**Describe alternatives you've considered**
I tried https://github.com/BingLingGroup/autosub. However, I keep encountering the following NameError, which is super strange (I've made sure autosub is installed):

```
NameError                                 Traceback (most recent call last)

<ipython-input-15-492003e58ef3> in <cell line: 1>()
----> 1 autosub -i /content/example.mp3

NameError: name 'autosub' is not defined
```

**Additional context**

**Comment by raryelcostasouza** [comment]
Sorry, I think I missed this notification. FYI apart from the local audio splitting using ffmpeg all the rest all runs on Google Cloud, so having a powerful GPU might not be the difference you would be expecting. For CLI usage I would recommend the original autosub at https://github.com/agermanidis/autosub.
