### ISSUE TITLE
Redirction error of pytranscriber website.

### ISSUE THREAD

**Issue by Xiang990293** [raryelcostasouza/pyTranscriber#39]
**Describe the bug**
The bug is on the feature log website: https://pytranscriber.github.io/
not the bug of application itself.
When click anything that is clickable, user will redirect to different website or advertisement.

**To Reproduce**
1. Go to ['the website write in README.md'](https://pytranscriber.github.io/)
2. Click on Download.
3. See error

**Expected behavior**
The website should redirecting user to download page, which is also under https://pytranscriber.github.io/, like https://pytranscriber.github.io/download

**Screenshots**

**Desktop:**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: (Browser) 123.0.2420.41

**Additional context**
I think the website got hacked, and I'm not sure if the country where user are changes the result.
I'm in Keelong, Taiwan. Hope that help you debug.

**Comment by raryelcostasouza** [comment]
Hi,

Thanks for reporting, but there are some redirecting ads enabled on the website for monetization. If it does not open the expected page on first try you can go back and retry and it usually works.

Thanks,
