### ISSUE TITLE
installers showing virus detected - MOVED TO NEW WEBSITE https://pytranscriber.github.io

### ISSUE THREAD

**Issue by TylerStilwagen** [raryelcostasouza/pyTranscriber#41]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by raryelcostasouza** [comment]
There was false positives earlier from Windows anti-malware and required me to submit a sample to Microsoft to confirm it was completely harmless. Let me check if they had a regression on this

**Comment by raryelcostasouza** [comment]
Please share the file you got flagged and what antimalware solution you are using

**Comment by raryelcostasouza** [comment]
Have you checked the SHA256 of the downloaded version? 
I do not see the installer being flagged by any major vendors https://www.virustotal.com/gui/file/245e6947859e25d97ba49a27fc3f58d195ce7f266b71f8dc020800b17645c45e. Could you please share what antimalware solution you are using for us to submit sample for their analysis and get this corrected?
