### ISSUE TITLE
Program window closes when clicking buttons (tests done on Ubuntu 20.04 and 22.04, with all program versions from 1.5 onwards)

### ISSUE THREAD

**Issue by ClaudioBoaventura** [raryelcostasouza/pyTranscriber#6]
Problems encountered, as summarized below:

Ubuntu Mate 20.04 (properly updated)
- To prevent the program window from closing (version 1.8, but basically the same thing happens with previous versions, both portable and installed), it is necessary every time to follow the sequence of clicks on the buttons: "Audio language", choose the program (Portuguese) and the "Output location", and finally "Select file" which will be transcribed to text (not following this step-by-step the window closes, using as "common" user, not tested as root)

Ubuntu Mate 22.04 (properly updated)
- Program closes the window (version 1.8, but basically the same with previous versions, both portable and installed), even doing the step-by-step previously reported with version 20.04 of Ubuntu Mate, using as a common user (as root you can use it, but makes it difficult due to the permissions of generated files being left to root, requiring changes to them manually)

**Comment by raryelcostasouza** [comment]
Thanks for the report... could you please try to run the app from the terminal window and send me the output you get there when it crashes?

**Comment by ClaudioBoaventura** [comment]
> Thanks for the report... could you please try to run the app from the terminal window and send me the output you get there when it crashes?

Of course, following messages from terminal:

claudio@notebook-Aspire-5920:~$ /opt/pyTranscriber/pyTranscriber
libGL error: MESA-LOADER: failed to open crocus: /usr/lib/dri/crocus_dri.so: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: crocus
libGL error: MESA-LOADER: failed to open crocus: /usr/lib/dri/crocus_dri.so: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: crocus
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast


(Below, error messages when clicking the buttons):

(pyTranscriber:2764): Gtk-WARNING **: 18:51:30.649: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/16x16/status/image-missing.png: Formato de arquivo de imagem não reconhecido (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/16x16/status/image-missing.png: Formato de arquivo de imagem não reconhecido (gdk-pixbuf-error-quark, 3)
Abortado (imagem do núcleo gravada)

**Comment by raryelcostasouza** [comment]
Please try installing the following package and see if the problem continues (solution from https://askubuntu.com/questions/1392138/problem-with-pygame-libgl-error-failed-to-load-driver-swrast):

sudo apt install libgl1-mesa-dri

**Comment by ClaudioBoaventura** [comment]
> Please try installing the following package and see if the problem continues (solution from https://askubuntu.com/questions/1392138/problem-with-pygame-libgl-error-failed-to-load-driver-swrast):
> 
> sudo apt install libgl1-mesa-dri

Thanks for help.
The package is already installed, in the latest version available in the repositories (22.0.5)

**Comment by raryelcostasouza** [comment]
Did the previous suggestion work?
If not how about running the following command from the terminal and then running pyTranscriber?
export MESA_LOADER_DRIVER_OVERRIDE=i965
/opt/pyTranscriber/pyTranscriber

**Comment by ClaudioBoaventura** [comment]
> Did the previous suggestion work? If not how about running the following command from the terminal and then running pyTranscriber? export MESA_LOADER_DRIVER_OVERRIDE=i965 /opt/pyTranscriber/pyTranscriber

Thanks a lot for the help.
The errors messages have changed, as displayed in the terminal (I believe it may be an error in the Mate environment, running on Ubuntu 22.04):

claudio@notebook-Aspire-5920:~$ export MESA_LOADER_DRIVER_OVERRIDE=i965
/opt/pyTranscriber/pyTranscriber

(pyTranscriber:8789): Gtk-WARNING **: 22:59:33.180: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/16x16/status/image-missing.png: Formato de arquivo de imagem não reconhecido (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Yaru/16x16/status/image-missing.png: Formato de arquivo de imagem não reconhecido (gdk-pixbuf-error-quark, 3)
Abortado (imagem do núcleo gravada)

**Comment by raryelcostasouza** [comment]
What video card you have on that laptop? Intel graphics or Nvidia/AMD?

**Comment by ClaudioBoaventura** [comment]
> What video card you have on that laptop? Intel graphics or Nvidia/AMD?

Intel 965GM (with maximum 384MB shared memory)

**Comment by raryelcostasouza** [comment]
Please run the 
$ export MESA_LOADER_DRIVER_OVERRIDE=i965
and then 
$ LIBGL_DEBUG=verbose /opt/pyTranscriber/pyTranscriber 
and paste here the output you get

**Comment by raryelcostasouza** [comment]
Did you try running the pyTranscriber-gnome40-wayland version or just the default one? That special version was compiled on a Ubuntu 22.04 running Gnome so it should be more compatible...

**Comment by ClaudioBoaventura** [comment]
> Did you try running the pyTranscriber-gnome40-wayland version or just the default one? That special version was compiled on a Ubuntu 22.04 running Gnome so it should be more compatible...

This version I hadn't tried yet, I installed it and it worked with a few tweaks:
- I changed the permissions of the files in the installation folder from "root" to my user;
- I manually copied the program shortcut to the desktop;
- Any sequence I follow to do the transcript is working without errors (I need to click the "Output Location" button every time, otherwise the window closes).

  As a suggestion, at least for me it would be very useful if the program supported other audio formats, for example ogg and opus (I don't know if there are limitations of AutoSub, if that's the way to continue using it in .mp3, but it's great).

Thank you very much for your effort to help, if you need any more information just ask me, congratulations and success with your project!!!

**Comment by raryelcostasouza** [comment]
In terms of audio formats... just try hard-renaming your ogg file to .mp3 for example and see if works... ffmpeg is the thing doing the conversions... so theoretically it should be able to convert basically anything...

**Comment by raryelcostasouza** [comment]
Good to hear you managed to get the app working... I will investigate the issue of the Output Location when possible... looks like a Mate related bug because on GNOME it works fine...
