### ISSUE TITLE
the latest version v1.8 is detected virus in Windows 10

### ISSUE THREAD

**Issue by benshgit** [raryelcostasouza/pyTranscriber#7]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by raryelcostasouza** [comment]
False positive... usually python apps that are frozen with pyInstaller confuse the Windows 10 antivirus... you can have a look at the code here... there is nothing malicious.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by raryelcostasouza** [comment]
Greetings,

I just tried here and it didn't detect anything wrong and I was able to download normally without any warnings... if you go to Windows Defender > Virus and Threat Detection > Threat History... what is the name of the supposed malware detected?

Go to Windows Defender and check you SmartScreen settings (App & browser control)... if it is setup as Block by default that behavior of deleting automatically will happen probably...

I will submit the app binaries to microsoft for analysis... so in a few days it should be whitelisted...

**Comment by raryelcostasouza** [comment]
But for reporting to Microsoft I need the detection name and your Defender definitions version.

**Comment by raryelcostasouza** [comment]
Just submitted to Microsoft for analysis https://www.microsoft.com/en-us/wdsi/submission/d06f11d7-7cfb-41f0-8c7b-f657c393c8ce and https://www.microsoft.com/en-us/wdsi/submission/0ccb999a-f106-474c-80d7-a1c9d6a7d8cf

**Comment by raryelcostasouza** [comment]
Microsoft replied that the files are clean... no detections

![image](https://user-images.githubusercontent.com/2302068/186902370-1e4307f2-3ce2-4369-86bd-fac60e2b4292.png)
![Screenshot from 2022-08-26 09-21-31](https://user-images.githubusercontent.com/2302068/186902429-8d73c811-d163-4e77-bd15-39b7023df251.png)

**Comment by benshgit** [comment]
Raryel,

Attached please refer the screenshots of the Threat History, and the Defender definitions version. I hope it can ***@***.******@***.******@***.***

Benjamin
