### ISSUE TITLE
Can it support audio in ogg format? 

### ISSUE THREAD

**Issue by zj1123581321** [raryelcostasouza/pyTranscriber#8]
Thank you very much for developing this, it helps me a lot!❤️❤️

Can it support audio in ogg format? Thank you very much!

The background is that I usually need to communicate with my Middle Eastern customers using Whatsapp, and the voice they send is downloaded in ogg format from the web version.

I would like to convert the ogg audio file to text directly to understand the customer's intention directly.

**Comment by raryelcostasouza** [comment]
Greetings,
If you rename the file from something.ogg to something.mp3 it will work.
I will have to update the file filter to include ogg files on the file chooser... but the underground converter (ffmpeg) already supports ogg... so renaming the files will work for now.

Best regards,
